### ISSUE TITLE
Avoid AndroidViewModel

### ISSUE THREAD

**Issue by shalomhalbert** [rocketinsights/q-streak-android#14]
Ironically, using `AndroidViewModel` violates MVVM conventions. One key principle behind how ViewModels should be built is that they should be totally context-unaware. Or, you could phrase it as: By passing in awareness of the `Application` you're making the ViewModel depend on the implementing class and vice-versa, when the relationship should be one-way.

**Comment by schmecs** [comment]
That's fair. I need to figure out the appropriate place to handle retrieving the `uid` from SharedPrefs - outside of the VMs I believe it would negate the need for `AndroidViewModel`. Probably should find a way to inject it with Koin.

**Comment by schmecs** [comment]
Inject SharedPrefs instead
