### ISSUE TITLE
Add Linter

### ISSUE THREAD

**Issue by juancruzgs** [rocketinsights/q-streak-android#21]
Add a Linter to automatically format your code.
It's really useful when there are multiple contributors with different code styles set.
I use this one that comes with the recommended Kotlin code style set by default https://github.com/pinterest/ktlint

**Comment by shalomhalbert** [comment]
Covered this in [Add Detekt](https://github.com/rocketinsights/q-streak-android/issues/9)

Detekt comes with KtLint and provides additional checks

**Comment by juancruzgs** [comment]
Cool, I didn't know that.
Will close this issue
